### ISSUE TITLE
ERR PuppetHostie start() rejection: connect ETIMEDOUT 104.31.73.129:443

### ISSUE THREAD

**Issue by sunshinearea** [juzibot/donut-tester#23]
Follow the instructions for running the demo, but report the following error after startup,
Token I've blurred.

18:06:24 SILL Config WECHATY_LOG set level to silly
18:06:24 INFO Config registering process.on("unhandledRejection") for development/debug
18:06:24 VERB Config constructor()
Debugger listening on ws://127.0.0.1:63171/e2c83044-0875-4086-a447-27395f045366
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
18:06:30 VERB Wechaty contructor()
18:06:30 VERB StateSwitch constructor(Wechaty, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
18:06:30 VERB StateSwitch constructor(WechatyReady, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
18:06:30 VERB Wechaty on(scan, function) registered
18:06:30 VERB Wechaty addListenerFunction(scan)
18:06:30 VERB Wechaty on(login, function) registered
18:06:30 VERB Wechaty addListenerFunction(login)
18:06:30 VERB Wechaty on(message, function) registered
18:06:30 VERB Wechaty addListenerFunction(message)
18:06:30 INFO Wechaty <wechaty-puppet-hostie>() start() v0.38.4 is starting...
18:06:30 VERB Wechaty id: ckbhrhr0d0000x9ud6j715wz3
18:06:30 SILL StateSwitch <Wechaty> on() is false
18:06:30 SILL StateSwitch <WechatyReady> off() is true
18:06:30 VERB StateSwitch <WechatyReady> off(true) <- (true)
18:06:30 SILL StateSwitch <Wechaty> on() is false
18:06:30 VERB StateSwitch <Wechaty> on(pending) <- (false)
18:06:30 VERB MemoryCard constructor(undefined)
18:06:30 VERB MemoryCard getStorage() for storage type: N/A
18:06:30 VERB MemoryCard load() from storage: N/A
18:06:30 VERB MemoryCard load() no storage
18:06:30 VERB Wechaty initPuppet() wechaty-puppet-hostie
18:06:30 VERB MemoryCard multiplex(puppet)
18:06:30 VERB MemoryCard static multiplex(MemoryCard<>, puppet)
18:06:30 VERB MemoryCard constructor({"multiplex":{"name":"puppet","parent":{"payload":{},"multiplexNameList":[]}}})
18:06:30 VERB PuppetManager resolve({puppet: wechaty-puppet-hostie, puppetOptions: {"token":"donut-test-user-"}})
18:06:30 VERB PuppetManager resolveName(wechaty-puppet-hostie)
18:06:30 VERB PuppetManager checkModule(wechaty-puppet-hostie)
18:06:30 SILL PuppetManager checkModule() wechaty-puppet-hostie installed version 0.6.1 satisfied range ^0.6.1
18:06:30 VERB Puppet constructor({"token":"donut-test-user-"}) #0
18:06:30 VERB StateSwitch constructor(PuppetHostie, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
18:06:30 VERB MemoryCard constructor(undefined)
18:06:30 VERB MemoryCard getStorage() for storage type: N/A
18:06:30 VERB MemoryCard load() from storage: N/A
18:06:30 VERB MemoryCard load() no storage
18:06:30 VERB Puppet constructor() watchdog timeout set to 60 seconds
18:06:30 VERB HotImport callerResolve(., /Users/sunshinearea/node_modules/wechaty-puppet/dist/src/puppet.js)
18:06:30 SILL HotImport callerResolve() callsites() file=/Users/sunshinearea/node_modules/hot-import/dist/src/hot-import.js, type=Object
18:06:30 SILL HotImport callerResolve() callsites() file=/Users/sunshinearea/node_modules/wechaty-puppet/dist/src/puppet.js, type=null
18:06:30 SILL HotImport callerResolve() callsites() file=/Users/sunshinearea/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js, type=null
18:06:30 SILL HotImport callerResolve() callerFile=/Users/sunshinearea/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js
18:06:30 VERB Puppet constructor() childClassPath=/Users/sunshinearea/node_modules/wechaty-puppet-hostie/dist/src/client
18:06:30 VERB Puppet constructor() memory.load() done
18:06:30 VERB Puppet setMemory()
18:06:30 VERB Wechaty initPuppetEventBridge(Puppet#0<PuppetHostie>())
18:06:30 VERB Wechaty initPuppetEventBridge() puppet.on(friendship) (listenerCount:0) registering...
18:06:30 VERB Wechaty initPuppetEventBridge() puppet.on(login) (listenerCount:0) registering...
18:06:30 VERB Wechaty initPuppetEventBridge() puppet.on(logout) (listenerCount:0) registering...
18:06:30 VERB Wechaty initPuppetEventBridge() puppet.on(message) (listenerCount:0) registering...
18:06:30 VERB Wechaty initPuppetEventBridge() puppet.on(room-invite) (listenerCount:0) registering...
18:06:30 VERB Wechaty initPuppetEventBridge() puppet.on(room-join) (listenerCount:0) registering...
18:06:30 VERB Wechaty initPuppetEventBridge() puppet.on(room-leave) (listenerCount:0) registering...
18:06:30 VERB Wechaty initPuppetEventBridge() puppet.on(room-topic) (listenerCount:0) registering...
18:06:30 VERB Wechaty initPuppetEventBridge() puppet.on(scan) (listenerCount:0) registering...
18:06:30 VERB Wechaty initPuppetEventBridge() puppet.on(dong) (listenerCount:0) registering...
18:06:30 VERB Wechaty initPuppetEventBridge() puppet.on(error) (listenerCount:0) registering...
18:06:30 VERB Wechaty initPuppetEventBridge() puppet.on(heartbeat) (listenerCount:1) registering...
18:06:30 VERB Wechaty initPuppetEventBridge() puppet.on(ready) (listenerCount:0) registering...
18:06:30 VERB Wechaty initPuppetEventBridge() puppet.on(reset) (listenerCount:1) registering...
18:06:30 VERB Wechaty initAccessory(Puppet#0<PuppetHostie>())
18:06:30 SILL Accessory <Contact> static set wechaty = "Wechaty#ckbhrhr0d0000x9ud6j715wz3<wechaty-puppet-hostie>()"
18:06:30 SILL Accessory <ContactSelf> static set wechaty = "Wechaty#ckbhrhr0d0000x9ud6j715wz3<wechaty-puppet-hostie>()"
18:06:30 SILL Accessory <Friendship> static set wechaty = "Wechaty#ckbhrhr0d0000x9ud6j715wz3<wechaty-puppet-hostie>()"
18:06:30 SILL Accessory <Image> static set wechaty = "Wechaty#ckbhrhr0d0000x9ud6j715wz3<wechaty-puppet-hostie>()"
18:06:30 SILL Accessory <Message> static set wechaty = "Wechaty#ckbhrhr0d0000x9ud6j715wz3<wechaty-puppet-hostie>()"
18:06:30 SILL Accessory <Room> static set wechaty = "Wechaty#ckbhrhr0d0000x9ud6j715wz3<wechaty-puppet-hostie>()"
18:06:30 SILL Accessory <RoomInvitation> static set wechaty = "Wechaty#ckbhrhr0d0000x9ud6j715wz3<wechaty-puppet-hostie>()"
18:06:30 SILL Accessory <Tag> static set wechaty = "Wechaty#ckbhrhr0d0000x9ud6j715wz3<wechaty-puppet-hostie>()"
18:06:30 SILL Accessory <Contact> static set puppet = "Puppet#0<PuppetHostie>()"
18:06:30 SILL Accessory <ContactSelf> static set puppet = "Puppet#0<PuppetHostie>()"
18:06:30 SILL Accessory <Friendship> static set puppet = "Puppet#0<PuppetHostie>()"
18:06:30 SILL Accessory <Image> static set puppet = "Puppet#0<PuppetHostie>()"
18:06:30 SILL Accessory <Message> static set puppet = "Puppet#0<PuppetHostie>()"
18:06:30 SILL Accessory <Room> static set puppet = "Puppet#0<PuppetHostie>()"
18:06:30 SILL Accessory <RoomInvitation> static set puppet = "Puppet#0<PuppetHostie>()"
18:06:30 SILL Accessory <Tag> static set puppet = "Puppet#0<PuppetHostie>()"
18:06:30 VERB PuppetHostie start()
18:06:30 SILL StateSwitch <PuppetHostie> on() is false
18:06:30 SILL StateSwitch <PuppetHostie> on() is false
18:06:30 VERB StateSwitch <PuppetHostie> on(pending) <- (false)
18:06:30 VERB PuppetHostie startGrpcClient()
18:06:30 VERB PuppetHostie discoverHostieIp(donut-test-user-)
18:07:46 ERR PuppetHostie start() rejection: connect ETIMEDOUT 104.31.73.129:443
18:07:46 SILL StateSwitch <PuppetHostie> off() is false
18:07:46 VERB StateSwitch <PuppetHostie> off(true) <- (false)
Error: connect ETIMEDOUT 104.31.73.129:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1126:14) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.31.73.129',
  port: 443
}
18:07:46 ERR Wechaty start() exception: connect ETIMEDOUT 104.31.73.129:443
18:07:46 ERR Config ###########################
18:07:46 ERR Config unhandledRejection: Error: connect ETIMEDOUT 104.31.73.129:443 [object Promise]
18:07:46 ERR Config ###########################
18:07:46 ERR Config process.on(unhandledRejection) promise.catch(connect ETIMEDOUT 104.31.73.129:443)
Config Error: connect ETIMEDOUT 104.31.73.129:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1126:14) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.31.73.129',
  port: 443
}
(node:40077) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
Waiting for the debugger to disconnect...

**Comment by huan** [comment]
There has some network related issues for our api.chatie.io IP, which is provided by the cloudflare.com service.

We believe that if you are running your program out side of the GFW it will be OK.

We will continue monitoring the network connectivities of the cloudflare.com service in China.

**Comment by sunshinearea** [comment]
@huan

**Comment by sunshinearea** [comment]
@huan

**Comment by sunshinearea** [comment]
@huan 
Can I connect my computer with over the wall enabled, and sometimes report the error, and does this endpoints require me to configure? What values need to be configured?Thanks.

18:32:10 ERR PuppetHostie start() rejection: no endpoint
18:32:10 SILL StateSwitch <PuppetHostie> off() is false
18:32:10 VERB StateSwitch <PuppetHostie> off(true) <- (false)
Error: no endpoint
    at PuppetHostie.<anonymous> (/Users/sunshinearea/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:85:27)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/sunshinearea/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
18:32:10 ERR Wechaty start() exception: no endpoint
18:32:10 ERR Config ###########################
18:32:10 ERR Config unhandledRejection: Error: no endpoint [object Promise]
18:32:10 ERR Config ###########################
18:32:10 ERR Config process.on(unhandledRejection) promise.catch(no endpoint)
Config Error: no endpoint
    at PuppetHostie.<anonymous> (/Users/sunshinearea/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:85:27)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/sunshinearea/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:40559) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
Waiting for the debugger to disconnect...

Process finished with exit code 0

**Comment by huan** [comment]
Sorry, I don't think you can "connect your computer with over the wall enabled" to your terminal programs, node.js in this case.

You have to make sure your TCP connections from the node program is not limited. Try to use a VPS outside of China will guarantee that.
