### ISSUE TITLE
启动报错,扫码没反应，登录不上

### ISSUE THREAD

**Issue by Mr-jiao** [juzibot/donut-tester#49]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. Please search in [FAQ List](https://wechaty.js.org/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions
- What is your wechaty version?
Answer:  wechaty@next

- What is your wechaty-puppet-donut version?
Answer:  "wechaty-puppet-hostie":  "^0.10.8",

- What is your node version? (run `node --version`)
Answer:  14.14.0

- What os are you using
Answer: mac os

## 2. Describe the bug
Error: 13 INTERNAL: no cache manager
    at Object.exports.createStatusError (/Users/mac2/Desktop/operationBot/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/mac2/Desktop/operationBot/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/Users/mac2/Desktop/operationBot/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/mac2/Desktop/operationBot/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/mac2/Desktop/operationBot/node_modules/grpc/src/client_interceptors.js:847:24) {
  code: 13,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'no cache manager'
}

## 3. To Reproduce
1. run npm start (just start the bot)

## 4. Expected behavior
no error

## 5. Actual behavior
![image](https://user-images.githubusercontent.com/44920775/99650391-5256a780-2a90-11eb-883e-0a86fc75ebc6.png)

## 6. Full Output Logs
Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

> bot@0.1.0 start /Users/mac2/Desktop/operationBot
> WECHATY_LOG=silly node bin/www

17:58:28 SILL Puppet Config: WECHATY_LOG set level to silly
17:58:28 INFO Config registering process.on("unhandledRejection") for development/debug
17:58:28 VERB Config constructor()
17:58:29 VERB Wechaty constructor()
17:58:29 VERB StateSwitch constructor(Wechaty, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
17:58:29 VERB StateSwitch constructor(WechatyReady, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
17:58:29 VERB Wechaty on(scan, listener) registering... listenerCount: 0
17:58:29 VERB Wechaty on(login, listener) registering... listenerCount: 0
17:58:29 VERB Wechaty on(logout, listener) registering... listenerCount: 0
17:58:29 VERB Wechaty on(message, listener) registering... listenerCount: 0
17:58:29 VERB Wechaty on(friendship, listener) registering... listenerCount: 0
17:58:29 VERB Wechaty on(room-invite, listener) registering... listenerCount: 0
17:58:29 VERB Wechaty on(room-join, listener) registering... listenerCount: 0
17:58:29 VERB Wechaty on(room-leave, listener) registering... listenerCount: 0
17:58:29 VERB Wechaty on(room-topic, listener) registering... listenerCount: 0
17:58:29 VERB Wechaty <wechaty-puppet-hostie>() start() v0.49.8 is starting...
17:58:29 VERB Wechaty id: ckhonwbv30000wgax6io1fhik
17:58:29 SILL StateSwitch <Wechaty> on() is false
17:58:29 SILL StateSwitch <WechatyReady> off() is true
17:58:29 VERB StateSwitch <WechatyReady> off(true) <- (true)
17:58:29 SILL StateSwitch <Wechaty> on() is false
17:58:29 VERB StateSwitch <Wechaty> on(pending) <- (false)
17:58:29 VERB MemoryCard constructor(undefined)
17:58:29 VERB MemoryCard getStorage() for storage type: N/A
17:58:29 VERB MemoryCard load() from storage: N/A
17:58:29 VERB MemoryCard load() no storage
17:58:29 VERB Wechaty initPuppet() wechaty-puppet-hostie
17:58:29 VERB MemoryCard multiplex(puppet)
17:58:29 VERB MemoryCard static multiplex(MemoryCard<>, puppet)
17:58:29 VERB MemoryCard constructor({"multiplex":{"name":"puppet","parent":{"payload":{},"multiplexNameList":[]}}})
17:58:29 VERB PuppetManager resolve({puppet: wechaty-puppet-hostie, puppetOptions: {"token":"puppet_donut_0ddbc6275167a5e1"}})
17:58:29 VERB PuppetManager resolveName(wechaty-puppet-hostie)
17:58:29 VERB PuppetManager checkModule(wechaty-puppet-hostie)
17:58:29 SILL PuppetManager checkModule() wechaty-puppet-hostie installed version 0.11.10 satisfied range *
17:58:29 VERB Puppet constructor({"token":"puppet_donut_0ddbc6275167a5e1"}) #0
17:58:29 VERB StateSwitch constructor(PuppetHostie, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
17:58:29 VERB MemoryCard constructor(undefined)
17:58:29 VERB MemoryCard getStorage() for storage type: N/A
17:58:29 VERB MemoryCard load() from storage: N/A
17:58:29 VERB MemoryCard load() no storage
17:58:29 VERB Puppet constructor() watchdog timeout set to 60 seconds
17:58:29 VERB HotImport callerResolve(., /Users/mac2/Desktop/operationBot/node_modules/wechaty-puppet/dist/src/puppet.js)
17:58:29 SILL HotImport callerResolve() callsites() file=/Users/mac2/Desktop/operationBot/node_modules/hot-import/dist/src/hot-import.js, type=Object
17:58:29 SILL HotImport callerResolve() callsites() file=/Users/mac2/Desktop/operationBot/node_modules/wechaty-puppet/dist/src/puppet.js, type=null
17:58:29 SILL HotImport callerResolve() callsites() file=/Users/mac2/Desktop/operationBot/node_modules/wechaty/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js, type=null
17:58:29 SILL HotImport callerResolve() callerFile=/Users/mac2/Desktop/operationBot/node_modules/wechaty/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js
17:58:29 VERB Puppet constructor() childClassPath=/Users/mac2/Desktop/operationBot/node_modules/wechaty/node_modules/wechaty-puppet-hostie/dist/src/client
17:58:29 VERB Puppet setMemory()
17:58:29 VERB Wechaty initPuppetEventBridge(Puppet#0<PuppetHostie>())
17:58:29 VERB Wechaty initPuppetEventBridge() puppet.on(friendship) (listenerCount:0) registering...
17:58:29 VERB Wechaty initPuppetEventBridge() puppet.on(login) (listenerCount:0) registering...
17:58:29 VERB Wechaty initPuppetEventBridge() puppet.on(logout) (listenerCount:0) registering...
17:58:29 VERB Wechaty initPuppetEventBridge() puppet.on(message) (listenerCount:0) registering...
17:58:29 VERB Wechaty initPuppetEventBridge() puppet.on(room-invite) (listenerCount:0) registering...
17:58:29 VERB Wechaty initPuppetEventBridge() puppet.on(room-join) (listenerCount:0) registering...
17:58:29 VERB Wechaty initPuppetEventBridge() puppet.on(room-leave) (listenerCount:0) registering...
17:58:29 VERB Wechaty initPuppetEventBridge() puppet.on(room-topic) (listenerCount:0) registering...
17:58:29 VERB Wechaty initPuppetEventBridge() puppet.on(scan) (listenerCount:0) registering...
17:58:29 VERB Wechaty initPuppetEventBridge() puppet.on(dirty) (listenerCount:0) registering...
17:58:29 VERB Wechaty initPuppetEventBridge() puppet.on(dong) (listenerCount:0) registering...
17:58:29 VERB Wechaty initPuppetEventBridge() puppet.on(error) (listenerCount:0) registering...
17:58:29 VERB Wechaty initPuppetEventBridge() puppet.on(heartbeat) (listenerCount:0) registering...
17:58:29 VERB Wechaty initPuppetEventBridge() puppet.on(ready) (listenerCount:0) registering...
17:58:29 VERB Wechaty initPuppetEventBridge() puppet.on(reset) (listenerCount:0) registering...
17:58:29 VERB Wechaty wechatifyUserModules(Puppet#0<PuppetHostie>())
17:58:29 VERB PuppetHostie start()
17:58:29 SILL StateSwitch <PuppetHostie> on() is false
17:58:29 SILL StateSwitch <PuppetHostie> on() is false
17:58:29 VERB StateSwitch <PuppetHostie> on(pending) <- (false)
17:58:29 VERB PuppetHostie startGrpcClient()
17:58:29 VERB PuppetHostie discoverHostieIp(puppet_donut_0ddbc6275167a5e1)
17:58:30 VERB PuppetHostie startGrpcStream()
17:58:30 VERB PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_SCAN(22), payload:"{"qrcode":"http://weixin.qq.com/x/w9KRG3IE2olBoH9GcJ5Z","status":2}"})
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▄▄▄ ▀▀ ▄▀▀▄▀ █ ▄▄▄▄▄ █
█ █   █ ██▄▀ █ ▀▀▀▀█ ██ █   █ █
█ █▄▄▄█ ██▀▄ ▄▄██ ▄█▄▀█ █▄▄▄█ █
█▄▄▄▄▄▄▄█ ▀▄█ ▀▄▀▄█▄█▄█▄▄▄▄▄▄▄█
█ ▄▀▄ ▀▄▀▀▄▀█▄▄ ▄▄ ▄▀▀█▄▀▀█▀▀▄█
█▀▄ █ ▀▄▄█▄██▄▄▀▄█ ▄█▀█▄▀▄█▄█▀█
███▄▄▄▄▄  ▄ █▀▀▀▀  ▀█▄▄  ▀▀█▀ █
█ ▀▀▄▄▀▄█▀▄ █▀██ █▄▄ ▄███▄▄ █ █
█▀ ▀▄█▀▄▄ █▀ ▄▀█▀█ █  ▀██▀▀▀▀██
█  ▄▀█▄▄▀ ██▀▄▀  ▄█ ▄▀ ▄█▄▀▀█▄█
█▄▄█▄▄▄▄█ ▀█▄▀██ ▀█▀▄ ▄▄▄  ▄▄██
█ ▄▄▄▄▄ ███▀ ▀█▀▄▄▀█  █▄█  █▀██
█ █   █ █ ▀▀▄▄▄█▄ █▄ ▄ ▄▄▄█▀▄▀█
█ █▄▄▄█ █▀▀▄ ▄█▀▄▀▄▄█▄█▀  ▀ ▄ █
█▄▄▄▄▄▄▄█▄▄▄█▄█▄██▄██▄███▄█████

StarterBot onScan: %s(%s) - %s Waiting 2 https://api.qrserver.com/v1/create-qr-code/?data=http%3A%2F%2Fweixin.qq.com%2Fx%2Fw9KRG3IE2olBoH9GcJ5Z
17:58:30 SILL StateSwitch <PuppetHostie> on() is pending
17:58:30 VERB StateSwitch <PuppetHostie> on(true) <- (pending)
17:58:30 VERB Wechaty on(heartbeat, listener) registering... listenerCount: 0
17:58:30 SILL StateSwitch <Wechaty> on() is pending
17:58:30 VERB StateSwitch <Wechaty> on(true) <- (pending)
StarterBot Starter Bot Started.
17:58:30 VERB Room findAll()
17:58:30 VERB Puppet roomSearch()
17:58:30 VERB PuppetHostie roomList()
17:58:30 VERB Room findAll() rejected: 13 INTERNAL: no cache manager
Error: 13 INTERNAL: no cache manager
    at Object.exports.createStatusError (/Users/mac2/Desktop/operationBot/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/mac2/Desktop/operationBot/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/Users/mac2/Desktop/operationBot/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/mac2/Desktop/operationBot/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/mac2/Desktop/operationBot/node_modules/grpc/src/client_interceptors.js:847:24) {
  code: 13,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'no cache manager'
}
17:58:41 VERB PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"debounce before login","timeout":60000}"})
17:58:41 SILL Wechaty memoryCheck() free: 97 MB, require: 4 MB
17:59:26 VERB PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"debounce before login","timeout":60000}"})
17:59:26 SILL Wechaty memoryCheck() free: 19 MB, require: 4 MB
17:59:56 VERB PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"debounce before login","timeout":60000}"})
17:59:56 SILL Wechaty memoryCheck() free: 89 MB, require: 4 MB
18:00:15 VERB PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_SCAN(22), payload:"{"qrcode":"http://weixin.qq.com/x/46h1SgneB3jl-j_YVHun","status":2}"})
18:00:15 SILL Wechaty memoryCheck() free: 170 MB, require: 4 MB


```

</details>

## 7. Additional context
[bug]

**Comment by su-chang** [comment]
升级下wechaty的版本后，继续测试下。

```shell
npm install wechaty
```

若仍有问题，联系`juzibot`附带此issue的链接。

**Comment by Mr-jiao** [comment]
还是会出现这个问题

**Comment by su-chang** [comment]
`wechaty@0.50.7`
`wechaty-puppet-hostie@0.11.5`

请再次确认，建议删除 node_modules 和 package-lock.json 后重新安装。

若仍有问题，发送token至 `juzibot` 并附带此issue的链接。
