### ISSUE TITLE
ERR Room ready() member.ready() exception

### ISSUE THREAD

**Issue by kangyaos** [juzibot/donut-tester#69]
Error: 13 INTERNAL: TIMEOUT, sync contact timeout, id: wxid_2m3jbp8b7vat22
    at Object.exports.createStatusError (E:\padplus-test\node_modules\grpc\src\common.js:91:15)
    at Object.onReceiveStatus (E:\padplus-test\node_modules\grpc\src\client_interceptors.js:1209:28)
    at InterceptingListener._callNext (E:\padplus-test\node_modules\grpc\src\client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (E:\padplus-test\node_modules\grpc\src\client_interceptors.js:618:8)
    at callback (E:\padplus-test\node_modules\grpc\src\client_interceptors.js:847:24)
14:51:08 ERR Room ready() member.ready() exception:
Error: 13 INTERNAL: TIMEOUT, sync contact timeout, id: wxid_5ozbz5v3xxms22
    at Object.exports.createStatusError (E:\padplus-test\node_modules\grpc\src\common.js:91:15)
    at Object.onReceiveStatus (E:\padplus-test\node_modules\grpc\src\client_interceptors.js:1209:28)
    at InterceptingListener._callNext (E:\padplus-test\node_modules\grpc\src\client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (E:\padplus-test\node_modules\grpc\src\client_interceptors.js:618:8)
    at callback (E:\padplus-test\node_modules\grpc\src\client_interceptors.js:847:24)

**Comment by shanjinlin2009** [comment]
有人解决了吗？

**Comment by zxypetre** [comment]
同问
