### ISSUE TITLE
toContact() is not supported in Donut

### ISSUE THREAD

**Issue by Charles-Wu-Chen** [juzibot/donut-tester#72]
https://wechaty.github.io/wechaty/#Message+toContact
This API is not support in Donut Puppet

**Is your feature request related to a problem? Please describe.**

When are user share a contact name card,  it would be handy to convert the message to contact and forward to others / other groups.  

**Describe the solution you'd like**

https://wechaty.github.io/wechaty/#Message+toContact, Implement it as official document described.

**Describe alternatives you've considered**

**Additional context**

Way to simulate the unsupported API error:
```
.on('message', async message => {
    console.log(`message: ${JSON.stringify(message)}`)
    if (message.type() === Message.Type.Contact) {
      console.log(await message.toContact())
    }
  })
```

Error log

21:31:06 VERB Message toContact()
21:31:06 VERB PuppetHostie messageContact(424415824494391865)
21:31:06 ERR Config ###########################
21:31:06 ERR Config unhandledRejection: Error: 13 INTERNAL: Wechaty Puppet Unsupported API Error. Learn More At https://github.com/wechaty/wechaty-puppet/wiki/Compatibility
    at Object.exports.createStatusError (/Users/wuc/nodejsproject/wechaty-getting-started/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/wuc/nodejsproject/wechaty-getting-started/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/Users/wuc/nodejsproject/wechaty-getting-started/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/wuc/nodejsproject/wechaty-getting-started/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/wuc/nodejsproject/wechaty-getting-started/node_modules/grpc/src/client_interceptors.js:847:24)
  code: 13,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details:
   'Wechaty Puppet Unsupported API Error. Learn More At https://github.com/wechaty/wechaty-puppet/wiki/Compatibility' }

[enhancement]

**Comment by su-chang** [comment]
It not supported now.
